### ISSUE TITLE
Collect posts form Telegram channels

### ISSUE THREAD

**Issue by qulaz** [qulaz/tg-exporter#1]
Create telegram bot that listen all [`channel_post`](https://core.telegram.org/bots/api#update) updates from Telegram API and stores all related data to out database.

Gotchas: 
1. In Telegram API every text message, photo, photo gallery and etc. - it's individual `channel_post` event. If user sent attachments in group, in every `channel_post` event must be field `media_group_id`. It's necessary to save it on our side as single post with multiple attachment. If the user sends a message with media group, then there will be a `caption` field in one of the `channel_post` events.
2. Each attachment type has its own data structure.
3. Telegram [does not provide static URLs](https://core.telegram.org/bots/api#getfile) for attachments. This is particularly important for photos, as we cannot rely on Telegram servers to display post photos. We need to download each photo and serve them ourselves to ensure a much better response time.

Tasks:
- [x] Tools for event bus (#3)
- [x] Process Telegram updates and send event about new channel post (#4)
- [x] Process events about new post published and save it to the database. Also, save photos from those posts (#5)
