### ISSUE TITLE
Endpoints for list of collected Telegram channels posts

### ISSUE THREAD

**Issue by qulaz** [qulaz/tg-exporter#2]
- [x] List of collected Telegram posts (#6)
- [x] Get tg channel by ID (#7)
- [x] Get list of available tg channels (#7)
